name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1', '1.0', '1.2.0', '^1.3.0-rc1']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia ${{ matrix.julia-version }}"
        uses: julia-actions/setup-julia@test/julia-versions2
      - run: julia -e 'println(\"Hello, World!\")'
